### PR TITLE
adds ingress template

### PR DESCRIPTION
**Pull request by michbeck100**

### CODE REVIEW

**Review by nic-6443 — COMMENTED** [review]
please upgrade chart version in `https://github.com/api7/api7-helm-chart/blob/69a734bea05b39c85f5e7b5b72812738afb17ec6/charts/api7/Chart.yaml#L18` too.

**Comment by michbeck100** [comment]
> please upgrade chart version in `Chart.yaml` too.
> 
> https://github.com/api7/api7-helm-chart/blob/69a734bea05b39c85f5e7b5b72812738afb17ec6/charts/api7/Chart.yaml#L18

Would you like me to set it to the next bugfix version (0.12.14), or increase the minor version to 0.13.0?

**Comment by michbeck100** [comment]
Updated chart version to 0.13.0 because it adds new features and is not a bugfix

**Review by nic-6443 — APPROVED** [review]

**Comment by nic-6443** [comment]
> Updated chart version to 0.13.0 because it adds new features and is not a bugfix

no problem.

**Review by moonming — APPROVED** [review]

**Review by bzp2010 — APPROVED** [review]

**Pull request merged**
